spring:
  
  datasource:
    url: jdbc:postgresql://db.ogbecfnwvnywudmcnwdg.supabase.co:5432/postgres
    username: postgres
    password: austrolopitecus

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
